#!/bin/bash

make install

function foo () {
    f="$1"

    res=$(/usr/bin/time -f "%U" tog -q --fastGetAbsName $@ 2>&1; exit $?)
    error=$?

    echo -e "-${error}-\t$res\t$f"
}
export -f foo


echo "== Files that should load"

for f in examples/working/*.agda; do
    sem -j+0 foo "$f"
done

sem --wait

echo "== Files that shouldn't load"

for f in examples/shouldfail/*.agda; do
    sem -j+0 foo "$f"
done

sem --wait
